#!/usr/bin/env python3
"""Builds the exercise library from the free-exercise-db project (public domain / Unlicense).

  curl -o exercises.json https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/dist/exercises.json
  python3 -I scripts/build-library.py exercises.json

Writes src/libraryIndex.ts (small index bundled in the app), public/lib/steps.json (loaded on demand)
and /tmp/lib-images.txt (the photo files to download and shrink with scripts/fetch-library-images.sh).
"""
import json, re, sys

src = sys.argv[1]
data = json.load(open(src))
MAIN_GEAR = {'barbell', 'dumbbell', 'cable', 'machine', 'body only', 'kettlebells', 'e-z curl bar', 'bands'}
GROUP = {  # muscle in the database -> (label shown in the app, day it belongs to)
    'chest': ('Chest', 'Push'), 'triceps': ('Triceps', 'Push'),
    'lats': ('Lats', 'Pull'), 'middle back': ('Mid back', 'Pull'), 'lower back': ('Lower back', 'Pull'),
    'traps': ('Traps', 'Pull'), 'biceps': ('Biceps', 'Pull'), 'forearms': ('Forearms', 'Pull'),
    'quadriceps': ('Quads', 'Legs'), 'hamstrings': ('Hamstrings', 'Legs'), 'glutes': ('Glutes', 'Legs'),
    'calves': ('Calves', 'Legs'), 'abductors': ('Hips', 'Legs'), 'adductors': ('Hips', 'Legs'),
    'shoulders': ('Shoulders', 'Shoulders/Abs'), 'abdominals': ('Abs', 'Shoulders/Abs'), 'neck': ('Neck', 'Shoulders/Abs'),
}
GEAR = {'barbell': 'gym', 'cable': 'gym', 'machine': 'gym', 'e-z curl bar': 'gym', 'dumbbell': 'db', 'kettlebells': 'db', 'body only': 'bw', 'bands': 'bw'}
# The database tags many isolation moves (flyes, pullovers, raises) as compound. Only real main lifts count as compound here.
MAIN_LIFT = re.compile(r'(press|row|squat|deadlift|pull-?up|chin-?up|pulldown|dip|lunge|thrust|clean|snatch|push-?up|rack pull|good morning|step-?up|hack|thruster)', re.I)
NOT_MAIN = re.compile(r'(fly|flye|pullover|raise|curl|extension|kickback|crunch|shrug|twist|plank|bridge|stretch|circle|wrist)', re.I)
is_main = lambda name: bool(MAIN_LIFT.search(name)) and not NOT_MAIN.search(name)
slug = lambda i: re.sub(r'[^a-z0-9-]', '-', i.lower().replace('_', '-'))

# Exercises you already have (hand-tuned) are not repeated from the library.
core_slugs = set(re.findall(r'": "([a-z0-9-]+)",?\n', open('src/exerciseMedia.ts').read().split('const MAP')[1].split('}')[0]))
core_names = set(n.lower() for n in re.findall(r"e\('[a-z0-9]+', '([^']+)'", open('src/data.ts').read()))
rows, steps, images = [], {}, []
for x in data:
    cat = x['category']
    mobility = False  # stretching is left out for now: the set logger counts reps, not hold times
    if not (cat in ('strength', 'powerlifting') and x.get('equipment') in MAIN_GEAR):
        continue
    pm = (x.get('primaryMuscles') or [''])[0]
    if pm not in GROUP and not mobility:
        continue
    label, day = GROUP.get(pm, (pm.capitalize() or 'Mobility', 'Full Body'))
    s = slug(x['id'])
    if s in core_slugs or x['name'].lower() in core_names:
        continue
    n = len(x.get('images', []))
    rows.append([s, x['name'], label, day, GEAR.get(x.get('equipment'), 'bw'), (x.get('equipment') or 'body only'),
                 {'beginner': 0, 'intermediate': 1, 'expert': 2}[x['level']], 1 if (x.get('mechanic') == 'compound' and is_main(x['name']) and not mobility) else 0, 1 if mobility else 0, n])
    steps[s] = {'name': x['name'], 'steps': x.get('instructions', []), 'primary': [p.capitalize() for p in x.get('primaryMuscles', [])], 'secondary': [p.capitalize() for p in x.get('secondaryMuscles', [])], 'n': n}
    for i, img in enumerate(x.get('images', [])):
        images.append(f"{img}\t{s}-{i}.jpg")

rows.sort(key=lambda r: (r[8], r[2], r[1]))
with open('src/libraryIndex.ts', 'w') as f:
    f.write("// Generated by scripts/build-library.py from free-exercise-db (public domain). Do not edit by hand.\n")
    f.write("// [slug, name, muscle, day, gear, equipment, level 0-2, compound 1/0, mobility 1/0, photos]\n")
    f.write("export type LibRow = [string, string, string, string, string, string, number, number, number, number]\n")
    f.write("export const LIB_ROWS: LibRow[] = " + json.dumps(rows, ensure_ascii=False, separators=(',', ':')) + "\n")
import os
os.makedirs('public/lib', exist_ok=True)
json.dump(steps, open('public/lib/steps.json', 'w'), ensure_ascii=False, separators=(',', ':'))
open('/tmp/lib-images.txt', 'w').write("\n".join(images) + "\n")
print(len(rows), 'exercises,', len(images), 'photos')
