// Question of the day: evergreen questions plus season and holiday questions that show up when the time comes.
export const EVERGREEN: string[] = [
 "What is the one song that guarantees a good set?",
 "What got you into lifting in the first place?",
 "What is your favorite lift and why?",
 "What is the best gym advice you have ever received?",
 "What is your go-to pre-workout meal?",
 "What is a small win you are proud of this week?",
 "What time did your alarm go off today?",
 "What is your current lift goal?",
 "Which exercise do you secretly dread?",
 "What is your favorite way to recover?",
 "What is one thing you do to stay consistent?",
 "Coffee before training: yes or no?",
 "What is your favorite post-workout meal?",
 "Who inspires you to keep showing up?",
 "What is your best PR so far?",
 "What is one habit you want to build this month?",
 "Leg day: love it or hate it?",
 "What do you listen to while you train?",
 "What is the most embarrassing gym moment you can share?",
 "What would you tell yourself on day one?",
 "Morning, lunch, or evening lifts, and why?",
 "What is your favorite kind of cardio?",
 "What is one exercise you want to master?",
 "How do you get through a day you do not want to train?",
 "What is your favorite gym snack?",
 "What is the heaviest thing you have ever lifted?",
 "What does your ideal rest day look like?",
 "What are you most grateful for in your fitness journey?",
 "If you could train with anyone, who would it be?",
 "What is your next fitness milestone?",
 "What is your favorite warm-up move?",
 "What is your least favorite part of the gym?",
 "What is your lucky piece of gym gear?",
 "Do you train better alone or with a partner?",
 "What is the first thing you do when you walk into the gym?",
 "What is your favorite muscle to train?",
 "What is your least favorite muscle to train?",
 "What is your go-to rest time between sets?",
 "How many hours of sleep do you aim for?",
 "What is your favorite protein source?",
 "What is a food you refuse to give up?",
 "What is your favorite meal-prep recipe?",
 "How much water do you drink on a training day?",
 "What is your favorite healthy swap?",
 "Do you track your food, or go by feel?",
 "What is your favorite cheat meal?",
 "What is the best thing you have eaten this week?",
 "What is your go-to breakfast on a lift day?",
 "Which supplement would you keep if you could only keep one?",
 "What is a healthy snack you actually enjoy?",
 "What helps you wind down after a hard session?",
 "How do you handle sore muscles?",
 "What is your favorite stretch?",
 "Do you foam roll, and does it help?",
 "What is your best tip for better sleep?",
 "How do you handle a bad training day?",
 "What do you do when you feel unmotivated?",
 "What is your favorite rest-day activity?",
 "How do you know when to push and when to back off?",
 "What is the best way you have found to de-stress?",
 "What is your favorite motivational quote?",
 "What is the best thing a workout has ever done for your mood?",
 "Who is the most encouraging person in your life?",
 "What is one thing you want to be known for?",
 "What does discipline mean to you?",
 "What does consistency look like on your hardest week?",
 "When did you last surprise yourself in the gym?",
 "What is something you used to think you could not do?",
 "What is a habit you quit that made you stronger?",
 "What is one thing you would do differently if you started over?",
 "What is a goal you hit that you once thought was impossible?",
 "What is your why?",
 "What keeps you coming back when it gets hard?",
 "What is the best workout you have ever had?",
 "What is your favorite way to celebrate a PR?",
 "Who would you thank for your fitness journey?",
 "What is one thing you are working on right now?",
 "What is your favorite lift to watch someone else do?",
 "What is the strangest piece of gym equipment you have used?",
 "What is the funniest thing you have seen at the gym?",
 "What is your gym pet peeve?",
 "What is your gym hot take?",
 "What is the most overrated exercise?",
 "What is the most underrated exercise?",
 "What is your favorite machine at the gym?",
 "Barbell, dumbbell, or machine?",
 "Do you prefer heavy and low reps, or lighter and high reps?",
 "What is your favorite rep range?",
 "Do you count reps out loud or silently?",
 "Do you chalk up, strap up, or neither?",
 "What is your favorite grip for pulling?",
 "Do you wear lifting shoes, flat shoes, or go barefoot?",
 "What is your favorite gym outfit?",
 "Do you use a lifting belt, and when?",
 "How long are your workouts, usually?",
 "What does a perfect session look like for you?",
 "What is your favorite day of the week to train?",
 "Which day do you skip most often, and why?",
 "How many days a week do you train?",
 "What is your go-to split?",
 "What is the best program you have ever followed?",
 "What is one lift you want to add 10 pounds to?",
 "What is your bench press goal?",
 "What is your squat goal?",
 "What is your deadlift goal?",
 "What is your pull-up goal?",
 "What is your running goal?",
 "How do you warm up before a heavy day?",
 "What is your favorite cooldown?",
 "What is your favorite lower-body finisher?",
 "What is your favorite arm exercise?",
 "What is your favorite shoulder exercise?",
 "What is your favorite back exercise?",
 "What is your favorite chest exercise?",
 "What is your favorite ab exercise?",
 "What is your favorite home workout?",
 "What is your favorite outdoor workout?",
 "What is your favorite way to move that is not lifting?",
 "How many steps do you aim for each day?",
 "Do you track your workouts in an app, a notebook, or in your head?",
 "What is the most useful thing you track?",
 "What number do you care about most: weight, reps, or how you feel?",
 "What is your favorite way to measure progress?",
 "Do you take progress photos?",
 "What did you notice first when you started to change?",
 "What is the best compliment you have received about your fitness?",
 "What is the nicest thing you have said to yourself after a workout?",
 "What is something you want to do with your strength?",
 "What is a physical goal that is not about looks?",
 "What activity are you training for outside the gym?",
 "Have you ever done a race, a meet, or a competition?",
 "What event would you love to train for?",
 "What is on your fitness bucket list?",
 "What is the farthest you have ever run?",
 "What is the longest hike you have ever done?",
 "What sport did you play growing up?",
 "What did your parents teach you about being active?",
 "What was your favorite playground game as a kid?",
 "What is your earliest exercise memory?",
 "What is your favorite way to play, not just train?",
 "How do you make workouts fun?",
 "What is your go-to playlist genre?",
 "What is the last podcast you listened to at the gym?",
 "What audiobook or podcast makes the time fly?",
 "What is your favorite gym movie?",
 "What is your favorite sports moment?",
 "Who is your favorite athlete and why?",
 "Who is your favorite fitness creator?",
 "What is the best fitness book you have read?",
 "What is the best piece of fitness content you have seen lately?",
 "What is one myth about fitness that drives you crazy?",
 "What is something you learned about training this year?",
 "What is something you learned about yourself in the gym?",
 "What mistake taught you the most?",
 "What injury taught you patience?",
 "How do you come back after a break?",
 "What is your plan for a busy week?",
 "How do you fit a workout into a packed day?",
 "What is your favorite 20-minute workout?",
 "What do you do when you only have 10 minutes?",
 "What is your go-to hotel-room workout?",
 "How do you stay on track while traveling?",
 "How do you stay on track at parties and events?",
 "How do you stay on track when you are sick of eating the same thing?",
 "What does your fridge always have in it?",
 "What is your favorite quick dinner?",
 "What is your favorite high-protein snack?",
 "What is your favorite smoothie?",
 "What is your favorite way to eat eggs?",
 "What is your favorite way to eat chicken?",
 "What is your favorite carb?",
 "What is your favorite vegetable?",
 "What is your favorite fruit?",
 "What is your favorite sauce or seasoning?",
 "What is one new food you tried recently?",
 "What is a recipe you want to master?",
 "Do you prep food for the week, and what is on the menu?",
 "What is the best $10 you have spent on fitness?",
 "What is the best fitness purchase you have made?",
 "What gym gear would you replace first?",
 "What do you keep in your gym bag?",
 "What is the one thing you always forget to pack?",
 "What is your morning routine?",
 "What is your evening routine?",
 "What is the first thing you do after a workout?",
 "What do you do in the first hour after you wake up?",
 "What is your favorite way to start a Monday?",
 "What is your favorite way to end a Friday?",
 "What does your ideal weekend look like?",
 "What is your Sunday reset?",
 "What do you do to prepare for the week ahead?",
 "What is one thing you can do tonight to make tomorrow easier?",
 "What is the smallest step you can take today?",
 "What is a habit you are proud of keeping?",
 "How long is your current streak?",
 "What is the longest streak you have ever had?",
 "What helps you protect your streak?",
 "What is the best thing about training with a crew?",
 "What do you want from this crew?",
 "What can you offer this crew?",
 "Who in your crew has motivated you lately?",
 "What is one thing you would tell a new member?",
 "What advice would you give to a beginner?",
 "What is a beginner mistake you made?",
 "What is a tip you wish someone told you sooner?",
 "What is one thing that made lifting less intimidating?",
 "What does a strong person look like to you?",
 "What does strong mean to you?",
 "What does healthy mean to you?",
 "What does progress mean to you?",
 "What do you do on a plateau?",
 "How do you deal with comparison?",
 "How do you celebrate small wins?",
 "What is one thing you did for yourself this week?",
 "What is one thing you did for someone else this week?",
 "How do you handle a missed workout?",
 "What is a rule you have for yourself?",
 "What is a boundary that helps you train?",
 "What does your support system look like?",
 "What is one fear you faced through fitness?",
 "What is one limit you pushed past?",
 "What did you do today that your past self would be proud of?",
 "What are you looking forward to this week?",
 "What is one word for how you feel today?",
 "How is your energy today, from 1 to 10?",
 "How is your body feeling today?",
 "How is your mind feeling today?",
 "What are you proud of from yesterday?",
 "What is your goal for today?",
 "What is your goal for this week?",
 "What is your goal for this month?",
 "What is your goal for this year?",
 "Where do you want to be in 90 days?",
 "What is one thing you will not compromise on?",
 "What is the best decision you have made for your health?",
 "What is something small that made a big difference?",
 "What do you want to improve about your routine?",
 "What would make your next workout great?",
 "What do you need from your crew today?",
 "If you had one more hour in the day, how would you spend it?",
 "If you could add one piece of equipment to every gym, what would it be?",
 "If you could design a workout for a friend, what would be in it?",
 "If you could master one skill, like a muscle-up or a handstand, which would it be?",
 "If you could travel anywhere to train, where would you go?",
 "If you could train in any era, which would you pick?",
 "If you could have dinner with one athlete, who would it be?",
 "If you could change one thing about your routine, what would it be?",
 "If you could give your younger self one tip, what would it be?",
 "If your workout had a theme song, what would it be?",
 "If your lifts had a nickname, what would it be?",
 "Describe your workout in three words.",
 "Describe your crew in three words.",
 "Describe your goals in three words.",
 "Describe your best day of training in one sentence.",
 "Describe the feeling after a great workout.",
 "Finish this sentence: I show up because...",
 "Finish this sentence: The hardest part is...",
 "Finish this sentence: I feel strongest when...",
 "Finish this sentence: Today I am grateful for...",
 "Finish this sentence: Next month I will...",
 "Finish this sentence: My body can...",
 "Finish this sentence: I am most proud of...",
 "Finish this sentence: My favorite thing about training is...",
 "Finish this sentence: One thing I am working on is...",
 "Finish this sentence: I could not do this without...",
 "Share a photo of your gym view today. What is it like?",
 "Share a photo of your post-workout meal. What is in it?",
 "Share a pic of your gym playlist. What is playing?",
 "Share a photo of your favorite place to train.",
 "Post a shoutout for someone in your crew.",
 "Share a win from this week, big or small.",
 "Share a struggle from this week. We have your back.",
 "Share one thing you learned this week.",
 "Share a tip that made your workouts better.",
 "Share a recipe your crew should try.",
 "Share a song that gets you moving.",
 "Share your favorite quote on discipline.",
 "Share the workout you are doing next.",
 "Share what you did before sunrise today.",
 "Share what you are doing for recovery today.",
 "Share your top three lifts right now.",
 "Share your must-have supplement, if any.",
 "Share a stretch that feels amazing.",
 "Share a goal you are chasing with a deadline.",
 "Share a number you want to hit.",
 "What is your why on a bad day?",
 "What does your crew mean to you?",
 "What is the best part of your day?",
 "What is your favorite part of showing up?",
 "What is one thing you love about your body?",
 "What is one thing your body did for you this week?",
 "Who do you want to see succeed?",
 "Who do you want to challenge this month?",
 "Which challenge would you like to see next in Will Power?",
 "What would you add to the app?",
 "What is the best streak story you have heard?",
 "What is a lesson fitness taught you about patience?",
 "What is a lesson fitness taught you about work ethic?",
 "What is a lesson fitness taught you about failure?",
 "What is a lesson fitness taught you about friendship?",
 "What is one thing you will try this week that you have never done?",
 "What is one thing you want to be better at than yesterday?",
 "What is the most satisfying part of a workout?",
 "What is the weirdest thing that motivates you?",
 "What is one thing you do that most people skip?",
 "What is your favorite kind of workout day: heavy, fast, or long?",
 "What is something you can do now that you could not a year ago?",
 "What is your favorite lift to finish a workout with?",
 "What is the best part of your pre-workout routine?",
 "What is one simple thing that boosts your energy?",
 "What is a food you love that people think is not healthy?",
 "What is your go-to excuse, and how do you beat it?",
 "What is the best workout partner trait?",
 "What is one gym rule you swear by?",
 "What is your favorite way to track your streak?",
 "What did you eat today that you are proud of?",
 "What small thing are you looking forward to after training?",
 "What does your best week of training look like?",
 "What is one thing you want your crew to hold you accountable for?",
 "What is something you do for fun that keeps you fit?",
 "What is the best thing you saw in the gym this week?"
]

export const SEASONAL: Record<'winter' | 'spring' | 'summer' | 'fall', string[]> = {
 "winter": [
  "What is your favorite way to stay warm before a cold-weather workout?",
  "How do you stay motivated when it is dark in the morning?",
  "What is your go-to indoor workout when it is freezing outside?",
  "What is your favorite cozy post-workout meal?",
  "How do you keep your routine when the weather is rough?",
  "What winter activity gets you moving, like skiing, skating, or sledding?",
  "What is your favorite warm drink after training?",
  "How do you beat the winter slump?",
  "What is your best tip for training in the cold?",
  "What does a snow day workout look like for you?",
  "How do you keep your immune system strong in winter?",
  "What is one cozy winter habit that helps you train?",
  "What is one small thing that makes winter training easier?",
  "What is one thing about winter you secretly enjoy?"
 ],
 "spring": [
  "What is your favorite thing about training as the weather warms up?",
  "What outdoor workout are you excited to start this spring?",
  "What is on your spring fitness reset list?",
  "What new habit are you planting this spring?",
  "What is your favorite spring run, walk, or ride?",
  "Are you a spring cleaner? What is your fitness version of it?",
  "What is your favorite fresh spring meal?",
  "What does spring training mean to you?",
  "What goal are you growing toward this season?",
  "How do you handle allergy season and still train?",
  "What is your favorite way to enjoy longer daylight?",
  "What outdoor spot are you excited to train at again?",
  "What does a fresh start look like for your training this spring?",
  "What is one thing you want to grow in your fitness this spring?"
 ],
 "summer": [
  "What is your favorite summer workout?",
  "How do you stay cool and hydrated when training in the heat?",
  "What is your go-to summer meal after a workout?",
  "What outdoor activity do you love most in summer?",
  "What is your favorite way to train on vacation?",
  "Are you a beach workout person or a pool workout person?",
  "What is your favorite summer fruit?",
  "How do you keep your routine through summer plans?",
  "What is your favorite summer sunrise or sunset workout?",
  "What is your summer fitness goal?",
  "What is your go-to way to cool down after training?",
  "What is one fun thing you want to do this summer that fitness makes possible?",
  "What is your favorite way to enjoy the long summer days?",
  "What is your favorite summer evening workout?"
 ],
 "fall": [
  "What is your favorite thing about training in fall weather?",
  "What is your favorite fall meal after a workout?",
  "What fall activity gets you moving, like hiking, apple picking, or football?",
  "How do you keep your routine as the days get shorter?",
  "What is your fall fitness goal?",
  "What does a fresh start in fall look like for you?",
  "What is your favorite cozy fall workout playlist?",
  "What is your best tip for training as it gets darker earlier?",
  "What is your favorite fall run or walk?",
  "What are you harvesting from this year of training?",
  "What is one thing you want to finish before the year ends?",
  "How do you keep momentum going into the holiday season?",
  "What is one thing you want to start before the year ends?",
  "What is one fall tradition that keeps you active?"
 ]
}

/** Questions for the day of, the day before, and two days before each holiday: [today, tomorrow, in two days]. */
export const HOLIDAY_QS: Record<string, { name: string; qs: string[] }> = {
 newyear: { name: "New Year’s Day", qs: ["Happy New Year! What is your one fitness word for this year?", "New Year’s Eve is over. What is the one goal you are chasing this year?", "The new year is almost here. What is a habit you are carrying forward?"] },
 mlk: { name: "MLK Day", qs: ["On MLK Day: what does serving others have to do with your fitness?", "MLK Day is coming up. What is something you are doing to lift up others?", "MLK Day is coming up. How does your crew show up for each other?"] },
 valentine: { name: "Valentine’s Day", qs: ["Happy Valentine’s Day! What do you love most about your fitness life?", "Valentine’s Day is tomorrow. How are you showing yourself some love this week?", "Valentine’s Day is almost here. Who would you want as a gym valentine?"] },
 presidents: { name: "Presidents’ Day", qs: ["Presidents’ Day: if you had a day off, what workout would you do?", "Long weekend coming up. What is your plan to stay active?", "Presidents’ Day weekend is almost here. What is the plan?"] },
 stpat: { name: "St. Patrick’s Day", qs: ["Happy St. Patrick’s Day! What are you feeling lucky about in your training?", "St. Patrick’s Day is tomorrow. What is your lucky lift?", "St. Patrick’s Day is coming. What is your plan to stay on track?"] },
 dstspring: { name: "Daylight saving (spring forward)", qs: ["We sprang forward. How are you adjusting to the lost hour?", "Clocks change this weekend. How do you protect your sleep and your streak?", "Daylight saving starts soon. Will you train earlier or later?"] },
 dstfall: { name: "Daylight saving (fall back)", qs: ["We fell back. What will you do with the extra hour?", "Clocks change this weekend. How will you use the extra hour?", "Daylight saving ends soon. How will it change your training time?"] },
 earth: { name: "Earth Day", qs: ["Happy Earth Day! What is your favorite way to train outside?", "Earth Day is tomorrow. What outdoor workout will you do?", "Earth Day is coming. What is your favorite trail or park?"] },
 easter: { name: "Easter", qs: ["Happy Easter! What is something you are celebrating this season?", "Easter is tomorrow. How are you staying active this weekend?", "Easter weekend is coming. What is the plan for food and fitness?"] },
 mothers: { name: "Mother’s Day", qs: ["Happy Mother’s Day! Who is the strongest mom you know?", "Mother’s Day is tomorrow. What did your mom teach you about being strong?", "Mother’s Day is coming. How would you celebrate a mom in your crew?"] },
 memorial: { name: "Memorial Day", qs: ["On Memorial Day: who are you remembering and honoring today?", "Memorial Day weekend is here. How are you staying active?", "Memorial Day weekend is coming. What is your plan?"] },
 fathers: { name: "Father’s Day", qs: ["Happy Father’s Day! Who is the strongest dad you know?", "Father’s Day is tomorrow. What did your dad teach you about hard work?", "Father’s Day is coming. How would you celebrate a dad in your crew?"] },
 juneteenth: { name: "Juneteenth", qs: ["On Juneteenth: what does freedom mean in your fitness journey?", "Juneteenth is tomorrow. What are you celebrating?", "Juneteenth is coming. How are you taking time to reflect?"] },
 july4: { name: "Independence Day", qs: ["Happy Fourth of July! What is your favorite way to celebrate and stay active?", "The Fourth is tomorrow. What is your plan for food and fitness?", "The Fourth of July is coming. Are you doing a holiday workout?"] },
 labor: { name: "Labor Day", qs: ["Happy Labor Day! What is the hardest-working thing you have done lately?", "Labor Day is tomorrow. How do you celebrate the work you put in?", "Labor Day weekend is coming. What is your plan?"] },
 halloween: { name: "Halloween", qs: ["Happy Halloween! What is your gym costume idea?", "Halloween is tomorrow. What is your spookiest workout?", "Halloween is coming. What is your plan with all that candy?"] },
 veterans: { name: "Veterans Day", qs: ["On Veterans Day: who are you thanking today?", "Veterans Day is tomorrow. How do you honor discipline in your life?", "Veterans Day is coming. What does service mean to you?"] },
 thanksgiving: { name: "Thanksgiving", qs: ["Happy Thanksgiving! What are you grateful for in your fitness journey?", "Thanksgiving is tomorrow. Are you doing a turkey trot or a morning workout?", "Thanksgiving is coming. What is your plan to enjoy it and stay on track?"] },
 blackfriday: { name: "Black Friday", qs: ["Black Friday: what fitness item is actually worth buying?", "Day after Thanksgiving: how are you moving after the feast?", "The holiday week is here. What is your plan to keep moving?"] },
 xmaseve: { name: "Christmas Eve", qs: ["It is Christmas Eve. What workout tradition do you have?", "Christmas Eve is tomorrow. What is your holiday fitness plan?", "Christmas is coming. How do you stay active around the holidays?"] },
 xmas: { name: "Christmas", qs: ["Merry Christmas! What are you grateful for this year?", "Christmas is tomorrow. What is your best holiday fitness tip?", "Christmas is almost here. What will you do to keep your streak alive?"] },
 nye: { name: "New Year’s Eve", qs: ["It is New Year’s Eve. What was your biggest win this year?", "New Year’s Eve is tomorrow. What are you proud of this year?", "The year is almost over. What do you want to finish strong?"] },
}

const utc = (y: number, m: number, d: number) => Date.UTC(y, m, d)
const DAY = 86400000
/** Nth weekday of a month (weekday: 0=Sun). */
const nth = (y: number, m: number, wd: number, n: number) => { const first = new Date(utc(y, m, 1)).getUTCDay(); return utc(y, m, 1 + ((wd - first + 7) % 7) + (n - 1) * 7) }
const lastWd = (y: number, m: number, wd: number) => { const last = new Date(utc(y, m + 1, 0)); return utc(y, m, last.getUTCDate() - ((last.getUTCDay() - wd + 7) % 7)) }
function easter(y: number) {
  const a = y % 19, b = Math.floor(y / 100), c = y % 100, d = Math.floor(b / 4), e = b % 4, f = Math.floor((b + 8) / 25)
  const g = Math.floor((b - f + 1) / 3), h = (19 * a + b - d - g + 15) % 30, i = Math.floor(c / 4), k = c % 4
  const l = (32 + 2 * e + 2 * i - h - k) % 7, m = Math.floor((a + 11 * h + 22 * l) / 451)
  return utc(y, Math.floor((h + l - 7 * m + 114) / 31) - 1, ((h + l - 7 * m + 114) % 31) + 1)
}
const holidayDates = (y: number): Record<string, number> => ({
  newyear: utc(y, 0, 1), mlk: nth(y, 0, 1, 3), valentine: utc(y, 1, 14), presidents: nth(y, 1, 1, 3), stpat: utc(y, 2, 17),
  dstspring: nth(y, 2, 0, 2), earth: utc(y, 3, 22), easter: easter(y), mothers: nth(y, 4, 0, 2), memorial: lastWd(y, 4, 1),
  fathers: nth(y, 5, 0, 3), juneteenth: utc(y, 5, 19), july4: utc(y, 6, 4), labor: nth(y, 8, 1, 1), halloween: utc(y, 9, 31),
  dstfall: nth(y, 10, 0, 1), veterans: utc(y, 10, 11), thanksgiving: nth(y, 10, 4, 4), blackfriday: nth(y, 10, 4, 4) + DAY,
  xmaseve: utc(y, 11, 24), xmas: utc(y, 11, 25), nye: utc(y, 11, 31),
})

export type Season = 'winter' | 'spring' | 'summer' | 'fall'
/** month is 1 to 12. */
export const seasonOf = (month: number, day: number): Season => {
  const md = month * 100 + day
  return md >= 1221 || md < 320 ? 'winter' : md < 621 ? 'spring' : md < 922 ? 'summer' : 'fall'
}

/** First day of the season this date is in (winter starts Dec 21 of the previous year for Jan to Mar dates). */
const seasonStart = (y: number, month: number /* 1 to 12 */, day: number): number => {
  const md = month * 100 + day
  if (md >= 1221) return utc(y, 11, 21)
  if (md < 320) return utc(y - 1, 11, 21)
  if (md < 621) return utc(y, 2, 20)
  if (md < 922) return utc(y, 5, 21)
  return utc(y, 8, 22)
}

export interface DailyQuestion { q: string; theme?: string }

/** The question for a date (YYYY-MM-DD). Holidays win, then a seasonal question about once a week, otherwise evergreen. */
export function questionFor(date: string): DailyQuestion {
  const [y, m, d] = date.split('-').map(Number)
  const t = utc(y, m - 1, d)
  for (const yr of [y, y + 1]) {
    const hd = holidayDates(yr)
    for (const [id, when] of Object.entries(hd)) {
      const off = Math.round((when - t) / DAY)
      if (off >= 0 && off <= 2) return { q: HOLIDAY_QS[id].qs[off], theme: HOLIDAY_QS[id].name }
    }
  }
  const dayIndex = Math.floor(t / DAY)
  if (dayIndex % 7 === 0) {
    const s = seasonOf(m, d)
    const start = seasonStart(y, m, d)
    return { q: SEASONAL[s][Math.floor((t - start) / DAY / 7) % SEASONAL[s].length], theme: s[0].toUpperCase() + s.slice(1) }
  }
  const k = dayIndex - Math.ceil(dayIndex / 7)
  return { q: EVERGREEN[k % EVERGREEN.length] }
}
